---
title: "Second graded lab"
author: "Karla Otoude"
format: html
---
```{r}
library(here)

here::i_am("lab-grades.Rproj")
```

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(vroom)
library(readr)
library(lubridate)
```

# Link to the github repository
https://github.com/Karla-O/lab-grades.git

# 1. Introduction 

## 1.1 Study organisation

### Question 1
```{r}
courses <- vroom(here("courses.csv"),
                col_types = cols(
    nb_grades = col_integer())) |> 
  rename(nb_exams = nb_grades)
```



### Question 2 
```{r}
courses |>
  summarise("course name" = course, 
            "identifier" = course_id,
            "module" = module,
            "number of exams" = nb_exams) |>
  arrange(courses$course) |>
  knitr::kable()
```

## 1.2 Students

### Question 3
```{r}
students <- vroom(here("students.csv"),
                col_types = cols(
    group = col_factor(), 
    id = col_integer(), 
    sex = col_factor()))
```
The `birth_date` column of the students data frame is of class `Date`.


## 1.3 Grades

### Question 4
```{r}
grades <- vroom(here("grades.csv"),
                     delim = ";", 
                     na = "unknown",
                col_types = cols(
                  id = col_integer(),
                  course_id = col_integer()
                ))
```


# 2. Student population analysis

### Question 5
```{r}
students |>
  ggplot(aes(x = group)) +
  geom_bar() + 
  labs(
    title = "Number of students per group",
    x = "Group",
    y = "Number of students"
  )
```


### Question 6
```{r}
students |>
  ggplot(aes(x = group, fill = sex)) +
  geom_bar() + 
  labs(
    title = "Gender representation in each group",
    x = "Group",
    y = "Number of students"
  )
```

### Question 7
```{r}
students |>
  mutate(age = round(time_length(today()-birth_date, unit="year"))) |>
  ggplot(aes(x = age)) +
  geom_histogram(binwidth = 1, fill = 'blue', color = "black") +
  labs(
    title = "Distribution of age among students",
    x = "Age",
    y = "Number of students"
  )
```

### Question 8
```{r}
students |>
  mutate(
    age = round(as.numeric((today() - birth_date) / dyears(1)))
  ) |>
  summarise(
    med_st = median(age, na.rm = TRUE),
   .by = group) |>
  arrange(group) |>
  knitr::kable()
```

### Question 9
```{r}
students |>
  mutate(
    "age" = round(as.numeric((today() - birth_date) / dyears(1)))
  ) |>
  filter(age == max(age), .by = group) |>
  select(id, sex, age, group) |>
  arrange(desc(age)) |>
  knitr::kable()
```


# Simple grade analysis

### Question 10
```{r}
nb_grades <- grades |> 
  filter(!is.na(grade)) |> 
  nrow()
```

The data set contains `r nb_grades`  grades 


### Question 11
```{r}
grades_per_course <- 
  left_join(grades, courses, by = "course_id")
all_info <- 
  left_join(grades_per_course, students, by = "id")

all_info |>
  filter(course == "Martial Arts and Self-Defense") |>
  group_by(group) |>
  summarise(mean_MASD = mean(grade, na.rm = TRUE)) |>
  ggplot(aes(x = group, y = mean_MASD)) +
  geom_col()
```

